apiVersion: tcg/v1alpha1
kind: ChangeSet
metadata:
  name: remove-checkout-requests
spec:
  changes:
    - id: remove-checkout-requests
      kind: metric_remove
      domain: prometheus
      from:
        domain: prometheus
        kind: metric
        name: checkout_requests_total
